// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBulqMsoxUjheC9LpdW6gobBTLbMq3BpCY',
    appId: '1:642412915143:web:0c1e37e7a1b6acfe5591e2',
    messagingSenderId: '642412915143',
    projectId: 'tasky-app-3c444',
    authDomain: 'tasky-app-3c444.firebaseapp.com',
    storageBucket: 'tasky-app-3c444.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQoGjtgWa4THKmesH1SFAKpU2Xrlsp2k8',
    appId: '1:642412915143:android:8e743ee2f8af4bd45591e2',
    messagingSenderId: '642412915143',
    projectId: 'tasky-app-3c444',
    storageBucket: 'tasky-app-3c444.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkyZD6RpFGbTuf1Wz0uSSjN0YWthn1e7I',
    appId: '1:642412915143:ios:40dfb5d22cb7282a5591e2',
    messagingSenderId: '642412915143',
    projectId: 'tasky-app-3c444',
    storageBucket: 'tasky-app-3c444.firebasestorage.app',
    iosBundleId: 'com.example.taskyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkyZD6RpFGbTuf1Wz0uSSjN0YWthn1e7I',
    appId: '1:642412915143:ios:40dfb5d22cb7282a5591e2',
    messagingSenderId: '642412915143',
    projectId: 'tasky-app-3c444',
    storageBucket: 'tasky-app-3c444.firebasestorage.app',
    iosBundleId: 'com.example.taskyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBulqMsoxUjheC9LpdW6gobBTLbMq3BpCY',
    appId: '1:642412915143:web:5eed21e9353468a15591e2',
    messagingSenderId: '642412915143',
    projectId: 'tasky-app-3c444',
    authDomain: 'tasky-app-3c444.firebaseapp.com',
    storageBucket: 'tasky-app-3c444.firebasestorage.app',
  );
}
